Automation repo template
paymongo/base-qa-automation pull request #1
Opened 2024-08-08 01:45 UTC by alexderilo

2024-08-08 06:57 UTC, papamai commented
Thank you sa initiative na to fren @alexderilo <3.

Baka pwede palagay na rin nito:
- DB Utilities - establish and disconnect DB keywords
- error keywords - utilities and assertions
- gitignore

Tapos paclean-up din nung _pycache_ directories.

2024-08-08 07:00 UTC, papamai commented on resources/keywords/db_assertions/common.robot
Xis, ito kahit isang keyword na lang lagay natin. HAHA

2024-08-08 07:06 UTC, alexderilo commented on resources/keywords/db_assertions/common.robot
oki na fren hahaha thanks

2024-08-08 07:07 UTC, papamai approved these changes

2024-08-08 07:12 UTC, seruuh approved these changes

2024-08-08 07:13 UTC, lorie143 requested changes
Hello @alexderilo can we also add the requests folder? thanks!

2024-08-08 07:13 UTC, lorie143 commented on tests/acceptance/documents.child.merchant-get/test_authentication.robot
> +    THEN response status code should be    200
Hello @alexderilo could you please check if we can add the following? thanks!
- add schema
- add assertions

2024-08-08 07:13 UTC, lorie143 commented on resources/keywords/assertions/common.robot
> +	[Arguments]    ${json_path}    ${expected_value}
fixed spacing

2024-08-08 07:13 UTC, lorie143 commented on resources/keywords/requests/core.organizations.id-get/request.robot
> +	${query_parameters}    set variable    ${EMPTY}
fix spacing

2024-08-08 07:13 UTC, lorie143 commented on resources/keywords/requests/core.organizations.id-get/request.robot
> +	FOR    ${param}    IN    @{query_param_list}
fix spacing

2024-08-08 07:13 UTC, lorie143 commented on resources/keywords/requests/core.organizations.id-get/request.robot
> +	log    ${response}
fix spacing

2024-08-08 07:13 UTC, lorie143 commented on resources/keywords/utilities/db_utilities.robot
> +	${DB_PASSWORD}    get decrypted text    ${${env}_DB_PASSWORD}
fix spacing

2024-08-09 02:28 UTC, lorie143 approved these changes
Approved on my end, thanks!

2024-08-09 03:52 UTC, marc-rint-paymongo approved these changes

2024-08-09 06:07 UTC, GOlmillaPM approved these changes
Looks good :) Thank you!

2024-08-09 06:08 UTC, merged